const mongoose = require('mongoose');
const doctorProfileSchema = new mongoose.Schema({
  user: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true },
  name: String,
  email: String,
  password: String,
  clinicName: String,
  clinicAddress: String,
  address: String,
  address2: String,
  city: String,
  state: String,
  pincode: String,
  phone: String,
  gender: String,
  weight: Number,
  height: Number,
  age: Number,
  blood: String,
  profileImage: String,       
  certFile: String,           
  photoID: String,            
  employmentProof: String,    
  specialization: { type: mongoose.Schema.Types.ObjectId, ref: 'Specialization' },
  experience: Number,
  bio: String,
  services: [{ type: mongoose.Schema.Types.ObjectId, ref: 'Service' }],
  schedule: [{ type: mongoose.Schema.Types.ObjectId, ref: 'Schedule' }],
  documents: [{ type: mongoose.Schema.Types.ObjectId, ref: 'Document' }],
  reviews: [{ type: mongoose.Schema.Types.ObjectId, ref: 'Review' }],
  earnings: { type: Number, default: 0 },
  avgRating: { type: Number, default: null },
  isApproved: { type: String, enum: ['pending', 'true', 'false'], default: 'pending' },
}, { timestamps: true });

module.exports = mongoose.model('DoctorProfile', doctorProfileSchema); 