const mongoose = require('mongoose');
const patientProfileSchema = new mongoose.Schema({
  user: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true },
  // User fields
  name: { type: String },
  firstName: { type: String },
  lastName: { type: String },
  email: { type: String },
  phone: { type: String },
  role: { type: String },
  gender: { type: String },
  isApproved: { type: String },
  avatar: { type: String },
  address: { type: String },
  address2: { type: String },
  city: { type: String },
  state: { type: String },
  country: { type: String },
  pincode: { type: String },
  age: { type: Number },
  blood: { type: String },
  weight: { type: Number },
  height: { type: Number },
  dob: { type: String },
  emergencyContact: { type: String },
  medicalInfo: { type: String },
  heartRate: { type: String },
  bp: { type: String },
  glucose: { type: String },
  allergies: { type: String },
  preExisting: { type: Boolean },
  medication: { type: Boolean },
  selectedMembers: { type: Object },
  childCount: { type: Number },
  memberDetails: { type: Object },
  profileImgUrl: { type: String },
  // PatientProfile-specific fields
  medicalHistory: String,
  documents: [{ type: mongoose.Schema.Types.ObjectId, ref: 'Document' }],
  appointments: [{ type: mongoose.Schema.Types.ObjectId, ref: 'Appointment' }],
}, { timestamps: true });

module.exports = mongoose.model('PatientProfile', patientProfileSchema); 